# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default='11111111111', max_length=50, verbose_name='联系方式'),
        ),
    ]
